### ISSUE TITLE
Ticker box 按星星沒有作用

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#1028]
登入後按星星，如果星星是空心，應該要讓它實心，如果是實心按了要變空心
-----
1. ticker 要改成 instId
2. 重新整理之後按了沒反應因為在按星星這邊，用 isConnectedRef.current 來判斷
3. 之前 API 跑很慢而且回傳 500 ，可能原因是回傳了兩次 json，回傳第二次會有錯誤，因為只有第一次回傳的時候會有 header 
    
    ```console
    Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
        at new NodeError (node:internal/errors:399:5)
        at ServerResponse.setHeader (node:_http_outgoing:645:11)
        at _res.setHeader (/home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/server/base-server.js:223:24)
        at sendJson (/home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/server/api-utils/node.js:194:9)
        at apiRes.json (/home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/server/api-utils/node.js:362:31)
        at handler (webpack-internal:///(api)/./src/pages/api/user/tickers/index.ts:23:25)
        at /home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/server/api-utils/node.js:377:16
        at /home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/server/lib/trace/tracer.js:92:36
        at NoopContextManager.with (/home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
        at ContextAPI.with (/home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
        at NoopTracer.startActiveSpan (/home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
        at ProxyTracer.startActiveSpan (/home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
        at /home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/server/lib/trace/tracer.js:81:107
        at NoopContextManager.with (/home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
        at ContextAPI.with (/home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
        at NextTracerImpl.trace (/home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/server/lib/trace/tracer.js:81:32)
        at Object.apiResolver (/home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/server/api-utils/node.js:375:63)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async DevServer.runApi (/home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/server/next-server.js:571:9)
        at async Object.fn (/home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/server/next-server.js:1018:35)
        at async Router.execute (/home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/server/router.js:297:32)
        at async DevServer.runImpl (/home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/server/base-server.js:522:29)
        at async DevServer.run (/home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/server/dev/next-dev-server.js:869:20)
        at async DevServer.handleRequestImpl (/home/shirley/cafeca/TideBit-DeFi/node_modules/next/dist/server/base-server.js:456:20) {
      digest: undefined
    }
    ```

**Comment by arealclimber** [comment]
taking 5 hrs

**Comment by arealclimber** [comment]
taking 2.5 hrs
- 更新首頁
- 更新財報pdf
- debug 這張票
