### ISSUE TITLE
Process handler

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#327]
加上 try-catch ，但想得到的發生情境應該用 context 回傳的 error code 跟 if-else 來寫

- [x] 拒絕簽名
- [x] 簽名內容過期
-----
- [x] open
- [x] update
- [x] close
- [x] withdraw
- [x] deposit
- [x] connect + sign service term

**Comment by arealclimber** [comment]
taking 2 hrs
remaining 2 hrs

**Comment by arealclimber** [comment]
### Throw & Catch exception 的流程

1. 整理 error 有哪些 (寫在 constants)
2. `Context` 裡呼叫的`function` 裡處理資料出現錯誤→ `catch` 下來並檢查 error code 是否為我們規範的格式；若不是，就 `throw CustomError`，把接到的 `error` 包成我們規範的樣子，這樣後面用到這個 `function` 的程式可以依此判斷；如果 Error 是我們規範的格式，就將 `Error` 包在 `result` 裡直接傳到下一層 (`return result`……)
3. `Component` 呼叫 `Context` 的 `function`，都應該拿到整理好的 `result`，拿 `result.code` 來判斷結果就可以；但錯誤可能出現在`Component` 呼叫 `Context`的過程，這時就要 `try-catch`，依照呼叫哪個 `function` 過程出現的錯誤，丟出對應 Error code 的 `CustomError` ， （例如整個 `try` 只呼叫 `createCFDOrder` ，就可以丟 `CFD_OPEN_FAILED` Exception，丟出適當的錯誤才方便除錯）
- function called by Context
- code logic in Context
- Context function called by Component

**Comment by arealclimber** [comment]
taking 6.5 hrs
remaining -- hrs

**Comment by arealclimber** [comment]
taking 6 hrs

**Comment by arealclimber** [comment]
```
close position error TypeError: Cannot read properties of undefined (reading 'currency')
    at _app-528120b5b827a71d.js:7:832741
    at Array.findIndex (<anonymous>)
    at eI (_app-528120b5b827a71d.js:7:832710)
    at _app-528120b5b827a71d.js:7:834464
    at s (main-1be8dd3a7dbb9822.js:1:95840)
    at u._invoke (main-1be8dd3a7dbb9822.js:1:95620)
    at e.<computed> [as next] (main-1be8dd3a7dbb9822.js:1:96243)
    at n (_app-528120b5b827a71d.js:27:9146)
    at a (_app-528120b5b827a71d.js:27:9343)
    at _app-528120b5b827a71d.js:27:9402
```
